datachecks/dcs-core

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation-request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

- Added conventional commit formatting, `docs, fix, feat` for the issue templates.
- Fixed the PR template issue linking.

feat(github): semantic issue templates

---

datachecks/__init__.py
datachecks/cli/cli.py
datachecks/core/common/models/configuration.py
datachecks/core/common/models/data_source_resource.py
datachecks/core/configuration/configuration.py
datachecks/core/configuration/configuration_parser.py
datachecks/core/datasource/manager.py
datachecks/core/inspect.py
datachecks/core/metric/base.py
datachecks/core/metric/manager.py
example_config.yaml
tests/core/configuration/test_configuration.py
tests/core/metric/test_metric_manager.py
tests/core/metric/test_numeric_metric.py
tests/core/test_inspect.py
tests/integration/conftest.py
tests/integration/datasource/test_search_datasource.py
tests/integration/datasource/test_sql_datasource.py
tests/integration/test_databases_availability.py
tests/integration/test_inspect.py
tests/utils.py

Change the configuration structure from 
```
product_db:
count_us_parts_valid:
metric_type: row_count        
table: products               
filters:
where_clause: "category = 'PARTS' AND is_valid is True and country_code = 'US'" 
```
```
metrics:
- name: count_us_parts
metric_type: document_count
resource: search_datastore.product_data_us
filters:
search_query: '{"match_all" : {}}'
```

refactor(configuration): update configuration structure

---

datachecks/core/datasource/search_datasource.py
tests/integration/datasource/test_search_datasource.py

- Querying list of indexes & fields metadata.

feat(profiling): opensearch auto detecting index and field 

---

datachecks/__version__.py
poetry.lock
pyproject.toml

version upgrade 0.2.0

---

.gitignore
docs/getting_started.md
docs/index.md
docs/integrations/opensearch.md
docs/integrations/postgres.md
docs/metrics/combined.md
docs/metrics/completeness.md
docs/metrics/numeric_distribution.md
docs/metrics/reliability.md
docs/metrics/uniqueness.md
mkdocs.yml

Added configuration documents for postgres

Docs structure

---

CNAME
datachecks/cli/cli.py
datachecks/core/common/errors.py
datachecks/core/configuration/configuration_parser.py
datachecks/core/datasource/opensearch.py
datachecks/core/datasource/postgres.py
datachecks/core/datasource/sql_datasource.py
datachecks/core/inspect.py
datachecks/core/metric/base.py
datachecks/core/metric/manager.py
datachecks/core/utils/log.py
datachecks/core/utils/tracking.py
example_config.yaml
tests/core/metric/test_reliability_metric.py
tests/integration/conftest.py
tests/integration/datasource/test_opensearch_datasource.py
tests/integration/datasource/test_postgres_datasource.py

Added datachecks error classes 
- `DataChecksConfigurationError`
- `DataChecksDataSourcesConnectionError`
- `DataChecksMetricGenerationError`
Use these errors to handle errors in different parts of the process

fix: added better error handle for inpect run

---

datachecks/cli/cli.py
datachecks/core/datasource/manager.py
datachecks/core/inspect.py
datachecks/core/metric/base.py
datachecks/core/profiling/datasource_profiling.py
datachecks/core/profiling/numeric_field_profiling.py
datachecks/core/profiling/text_field_profiling.py
mkdocs.yml
poetry.lock
pyproject.toml
tests/cli/__init__.py
tests/cli/run_cli.py
tests/cli/test_cli.py
tests/cli/test_config.yaml

Added improved CLI output for metrics

feat: add CLI output for metrics

---

README.md
docs/configuration/datasource_configuration.md
docs/configuration/metric_configuration.md
docs/getting_started.md
docs/integrations/opensearch.md
docs/metrics/combined.md
docs/metrics/completeness.md
docs/metrics/numeric_distribution.md
docs/metrics/reliability.md
docs/metrics/uniqueness.md
docs/support/contact.md
docs/support/usage_analytics.md
mkdocs.yml

Documentation update for configuration

docs: update configuration documentation

---

docs/support/usage_analytics.md

docs:  Update usage_analytics

---

datachecks/__version__.py
pyproject.toml

bump up version to 0.2.1

---

README.md
datachecks/core/datasource/manager.py
datachecks/integrations/databases/elasticsearch.py
docker-compose-test.yaml
docs/integrations/elasticsearch.md
docs/integrations/opensearch.md
mkdocs.yml
poetry.lock
pyproject.toml
tests/core/configuration/test_configuration.py
tests/integration/datasource/test_elasticsearch_datasource.py

Added elasticsearch datasource

feat: add elasticsearch data source

---

datachecks/core/common/models/metric.py
datachecks/core/datasource/search_datasource.py
datachecks/core/datasource/sql_datasource.py
datachecks/core/metric/manager.py
datachecks/core/metric/numeric_metric.py
tests/core/metric/test_metric_manager.py
tests/core/metric/test_numeric_metric.py
tests/integration/datasource/test_search_datasource.py
tests/integration/datasource/test_sql_datasource.py

- Added `EmptyStringCountMetric` class, and initiated tests.
- Added a few example cases to test with.

feat(metrics): added empty-string-count and tests

---

README.md
datachecks/core/datasource/manager.py
datachecks/integrations/databases/mysql.py
docker-compose-test.yaml
docs/integrations/mysql.md
mkdocs.yml
poetry.lock
pyproject.toml
tests/core/configuration/test_configuration.py
tests/integration/datasource/test_mysql_datasource.py

feat: add mysql data source

---

datachecks/core/common/models/metric.py
datachecks/core/datasource/search_datasource.py
datachecks/core/datasource/sql_datasource.py
datachecks/core/metric/manager.py
datachecks/core/metric/numeric_metric.py
tests/core/metric/test_metric_manager.py
tests/core/metric/test_numeric_metric.py
tests/integration/datasource/test_search_datasource.py
tests/integration/datasource/test_sql_datasource.py

- Added the empty-string-percentage metric with classes.
- Tested initialisation using mock data, and integration tests with the DB.

feat(metrics): implemented empty-string-percentage metric and tests

---

README.md
docs/support/contact.md
mkdocs.yml

docs: add slack channel to readme

---

datachecks/core/metric/base.py
datachecks/core/metric/manager.py
tests/core/metric/test_metric_manager.py

Filters field in metric config aren't affecting in results

fix(metric): the metric configuration filters does not apply

---

docs/configuration/metric_configuration.md
docs/metrics/combined.md
docs/metrics/completeness.md
docs/metrics/numeric_distribution.md
docs/metrics/uniqueness.md
mkdocs.yml

Update metric configuration documentation.

docs: update metric configurations

---

mkdocs.yml

docs: added tracking for docs

---

datachecks/__version__.py
pyproject.toml

bump up version to 0.2.2

---

datachecks/__version__.py
pyproject.toml

bump up version to 0.2.3

---

docs/configuration/metric_configuration.md
docs/getting_started.md
docs/metrics/numeric_distribution.md
docs/metrics/reliability.md

Update validation documentation

docs: update validation docs

---

docs/configuration/metric_configuration.md
docs/getting_started.md

docs: fix docs failure

---

datachecks/report/dashboard.py
datachecks/report/models.py
example_config.yaml

Refactoring API Dashboard contracts and added following attributes:
1. Metrics:
1. metric_validation_unchecked

refactor(dashboard): Update dashboard contracts

---

README.md
datachecks/core/common/models/configuration.py
datachecks/core/common/models/metric.py
datachecks/core/configuration/configuration_parser.py
datachecks/core/datasource/sql_datasource.py
datachecks/core/inspect.py
datachecks/core/metric/base.py
datachecks/core/metric/custom_metric.py
datachecks/core/metric/manager.py
datachecks/report/models.py
docs/configuration/metric_configuration.md
docs/metrics/custom_sql.md
example_config.yaml
mkdocs.yml
tests/core/configuration/test_configuration.py
tests/core/metric/test_metric_manager.py
tests/integration/datasource/test_sql_datasource.py

feat: add custom sql metric

---

README.md
datachecks/core/common/models/configuration.py
datachecks/core/datasource/manager.py
datachecks/integrations/databases/mssql.py
poetry.lock
pyproject.toml

[DCS-195] add sql server integration

---

README.md
docs/integrations/mssql.md
docs/integrations/snowflake.md

Documentation for SQL Server and Snowflake

[DCS-195] add sql server documentation

---

mkdocs.yml

[DCS-193] add snowflake docs

---

poetry.lock
pyproject.toml

[DCS-193] fix mssql dependency

---

datachecks/__version__.py
pyproject.toml

upgrade to v0.3.0

---

README.md
datachecks/core/datasource/sql_datasource.py
datachecks/core/validation/manager.py
datachecks/core/validation/validity_validation.py
docs/configuration/metric_configuration.md
docs/validations/validity.md
mkdocs.yml
tests/core/configuration/test_configuration_v1.py
tests/integration/datasource/test_sql_datasource.py

Validity function for `count_uuid` and `percent_uuid`

feat: [DCS-210] add count_uuid and percent_uuid functions

---

.github/workflows/ci.yml
tests/integration/configuration/test_configurations.py
tests/integration/configuration/test_configurations_v1.py
tests/integration/conftest.py

fix: tests configurations issue

---

datachecks/core/datasource/sql_datasource.py
datachecks/core/validation/manager.py
datachecks/core/validation/validity_validation.py
docs/validations/validity.md
tests/core/configuration/test_configuration_v1.py
tests/integration/datasource/test_sql_datasource.py

Validity function for `count_email` and `percent_email`

feat: [DCS-225] add count_email and percent_email functions

---

datachecks/core/datasource/sql_datasource.py
datachecks/core/validation/manager.py
datachecks/core/validation/validity_validation.py
docs/validations/validity.md
examples/configurations/postgres/example_postgres_config.yaml
tests/core/configuration/test_configuration_v1.py
tests/integration/datasource/test_sql_datasource.py

feat: add string length validators and tests

---

datachecks/core/datasource/sql_datasource.py
datachecks/core/validation/manager.py
datachecks/core/validation/validity_validation.py
docs/validations/validity.md
examples/configurations/postgres/example_postgres_config.yaml
tests/core/configuration/test_configuration_v1.py
tests/integration/datasource/test_sql_datasource.py

feat: Geolocation Validity Metrics

---

datachecks/core/common/models/validation.py
datachecks/core/datasource/sql_datasource.py
datachecks/core/validation/manager.py
datachecks/core/validation/numeric_validation.py
docs/validations/numeric_distribution.md
examples/configurations/postgres/example_postgres_config.yaml
tests/core/configuration/test_configuration_v1.py
tests/integration/datasource/test_sql_datasource.py

feat: percentile Numeric validation function

---

dcs_core/__version__.py
poetry.lock
pyproject.toml

upgrade to V0.4.0

---

dcs_core/integrations/databases/mssql.py

fix: mssql database connect

---

dcs_core/__version__.py
poetry.lock
pyproject.toml

upgrade to v0.5.0

---

dcs_core/core/configuration/configuration_parser.py
dcs_core/core/datasource/sql_datasource.py
dcs_core/integrations/databases/db2.py
dcs_core/integrations/databases/mssql.py
dcs_core/integrations/databases/mysql.py
dcs_core/integrations/databases/sybase.py

fix: sybase custom query

---

dcs_core/core/common/models/configuration.py
dcs_core/core/configuration/configuration_parser.py
dcs_core/core/datasource/sql_datasource.py
dcs_core/integrations/databases/sybase.py

https://github.com/datachecks/dcs-core/issues/280 https://github.com/datachecks/dcs-core/issues/281

fix: sybase IQ driver & sql connection engine dispose

---

.github/workflows/ci.yml
dcs_core/core/common/models/data_source_resource.py
dcs_core/core/datasource/sql_datasource.py
dcs_core/integrations/databases/db2.py
dcs_core/integrations/databases/mssql.py
dcs_core/integrations/databases/mysql.py
dcs_core/integrations/databases/oracle.py
dcs_core/integrations/databases/postgres.py
dcs_core/integrations/databases/sybase.py

feat: get column/tables details from query, quoted columns/tables/database

---

dcs_core/core/common/models/configuration.py
dcs_core/core/configuration/configuration_parser.py
dcs_core/core/configuration/configuration_parser_arc.py
dcs_core/integrations/databases/bigquery.py
tests/core/configuration/test_configuration.py
tests/core/configuration/test_configuration_v1.py

feat: bigquery query table/columns names with schema prefix

---

dcs_core/__version__.py
pyproject.toml

chore: version bump v0.8.5

---

poetry.lock
pyproject.toml

Other
___
- Change setuptools dependency constraint from caret to greater-than-or-equal-to
___
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>pyproject.toml</strong><dd><code>Update setuptools dependency constraint</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pyproject.toml
<ul><li>Modified setuptools dependency constraint from "^78.1.1" to ">=78.1.1"</ul>
</details>
</td>
<td><a href="https://github.com/datachecks/dcs-core/pull/327/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd …

fix: dependency

---

dcs_core/__version__.py
pyproject.toml

chore: bump version to 0.9.3
