datachecks/dcs-core

datachecks/core/inspect.py, datachecks/core/metric/base.py, datachecks/core/utils/__init__.py, datachecks/core/utils/tracking.py, datachecks/core/utils/utils.py, tests/core/test_inspect.py
Implement rudderlabs tacking for inspect runs
=> feat(metric): add anonymous tracking for inspect

datachecks/core/datasource/search_datasource.py, tests/integration/datasource/test_search_datasource.py
- Querying profiling for numeric & text fields in search index datasources.
=> feat(profiling): automatic datasource profiling for search index datasources

datachecks/cli/cli.py
Updated structure for the CLI metric table
=> feat: update cli table output

docs/index.md, docs/metrics/combined.md, docs/metrics/completeness.md, docs/metrics/numeric_distribution.md, docs/metrics/uniqueness.md
=> docs: update website-docs

datachecks/core/datasource/sql_datasource.py
Noted, and changed all instances in query to enable `qualified_table_name` to it instead of the original table name.
=> fix(datasource): included qualified_table_name to all table calls

README.md
Fixes line 107 that indicates access to the access link as issues from https://github.com/waterdipai/datachceks/issues to https://github.com/waterdipai/datachecks/issues.
=> docs: fix the issue link

datachecks/core/datasource/manager.py
While using various databases, Importing module isn't identifying the which modules to import.
=> fix(import): modules to import isn't being identifiable

datachecks/core/datasource/sql_datasource.py, tests/integration/test_databases_availability.py
Usage of round function average and variance, is rendered unusable in Postgres SQL.
=> fix(metrics): round function in average and variance metric

datachecks/core/configuration/configuration_parser.py
opensearch and elasticsearch in freshness metric is not accepting field_name.
=> fix(metric): field_name not being accepted in open-search and elastic-search in freshness metric

datachecks/cli/cli.py, datachecks/core/common/models/configuration.py, datachecks/core/common/models/metric.py, datachecks/core/common/models/validation.py, datachecks/core/configuration/configuration_parser.py, datachecks/core/metric/base.py, datachecks/core/metric/combined_metric.py, datachecks/core/metric/manager.py, tests/core/configuration/test_configuration.py, tests/core/metric/test_combined_metric.py, tests/core/metric/test_metric_manager.py, tests/core/metric/test_numeric_metric.py, tests/core/metric/test_reliability_metric.py
```
metrics:
- name: test-met
resource: d.t.c
type: min
validation:
threshold: >= 9 & <= 11 | = 9 | < 9 | > 9 | >= 9 | <= 9
```
=> feat(validation): metric validation framework

README.md, datachecks/core/datasource/manager.py, datachecks/integrations/databases/redshift.py, docs/integrations/redshift.md, mkdocs.yml, poetry.lock, pyproject.toml
New integration for Redshift.
Using [Redshift sqlalchemy](https://pypi.org/project/sqlalchemy-redshift/) to make the connection with Redshift.
=> feat(datasource): aws redshift datasource

datachecks/report/dashboard.py, datachecks/report/models.py
Generating HTML report at datachecks_report.html
Failed to run datachecks inspection: Object of type Decimal is not JSON serializable
=> fix(dashboard): type decimal is not json serializable in html report generation

datachecks/core/configuration/configuration_parser.py, tests/core/configuration/test_configuration.py
Fixed the bug where duplicate metric names were not detected. This update generates an error and shows the names of the duplicate metrics
=> fix: duplicate metric names

datachecks/core/metric/base.py, tests/core/metric/test_metric_manager.py, tests/core/metric/test_numeric_metric.py, tests/core/metric/test_reliability_metric.py
=> fix(filters): filter option application fixed

examples/configurations/example_bigquery_config.yaml, examples/configurations/example_databricks_config.yaml, examples/configurations/example_elasticsearch_config.yaml, examples/configurations/example_mysql_config.yaml, examples/configurations/example_opensearch_config.yaml, examples/configurations/example_postgres_config.yaml, examples/configurations/example_redshift_config.yaml
- In `examples\configurations` - data_sources name is suffixed with type of database.
=> refactor: example configurations suffixed with data sources type

examples/configurations/example_postgres_config.yaml
Renamed the datasource name from iris to iris_pgsql inside the configuration file example_postgres_config.yaml
=> fix(typo): renamed datasource iris to iris_pgsql

datachecks/core/datasource/sql_datasource.py
Get table name from defined `schema`
Remove `schema` param from `get_table_names` method, if schema is not passed it'll use default schema for the database.
=> fix: sql schema hardcoded in method query_get_table_metadata  #212

datachecks/core/datasource/sql_datasource.py, datachecks/core/validation/manager.py, datachecks/core/validation/validity_validation.py, tests/core/configuration/test_configuration_v1.py, tests/integration/datasource/test_sql_datasource.py
Validity functions for: 
- `count_usa_state_code`
- `percent_usa_state_code`
- `count_usa_zip_code`
- `percent_usa_zip_code`
=> feat: [DCS-230] add usa state code and zip code validations

dcs_core/core/common/models/validation.py, dcs_core/core/datasource/sql_datasource.py, dcs_core/core/validation/manager.py, dcs_core/core/validation/numeric_validation.py, docs/validations/validity.md, examples/configurations/postgres/example_postgres_config.yaml, tests/core/configuration/test_configuration_v1.py, tests/integration/datasource/test_sql_datasource.py
=> feat: zero numeric validation function

dcs_core/core/common/models/validation.py, dcs_core/core/datasource/manager.py, dcs_core/core/datasource/sql_datasource.py, dcs_core/core/validation/completeness_validation.py, dcs_core/core/validation/manager.py, docs/validations/validity.md, tests/core/configuration/test_configuration_v1.py, tests/integration/datasource/test_sql_datasource.py
Validity function for count all space and percent all space
=> feat: [DCS-247] add count_all_space and percent_all_space functions

dcs_core/core/common/models/validation.py, dcs_core/core/datasource/sql_datasource.py, dcs_core/core/validation/completeness_validation.py, dcs_core/core/validation/manager.py, docs/validations/validity.md, tests/core/configuration/test_configuration_v1.py, tests/integration/datasource/test_sql_datasource.py
Validity function for count null keyword and percent null keyword
=> feat: [DCS-248] add count_null_keyword and percent_null_keyword functions

dcs_core/core/datasource/sql_datasource.py, dcs_core/core/validation/manager.py, dcs_core/core/validation/validity_validation.py, docs/validations/validity.md, tests/core/configuration/test_configuration_v1.py, tests/integration/datasource/test_sql_datasource.py
Validity function for 
count_timestamp_string and  percent_timestamp_string,
count_not_in_future and percent_count_not_in_future,
count_date_not_in_future and percent_date_not_in_future 
=> feat: [DCS-245]  Timestamp Validity Metric

dcs_core/core/datasource/sql_datasource.py, dcs_core/core/validation/completeness_validation.py, dcs_core/core/validation/numeric_validation.py, dcs_core/core/validation/reliability_validation.py, dcs_core/core/validation/uniqueness_validation.py, dcs_core/core/validation/validity_validation.py, dcs_core/integrations/databases/oracle.py, tests/integration/datasource/test_sql_datasource.py
- Fixes validation queries for Oracle DB  #269 
=> fix: validation queries for oracle db

dcs_core/core/datasource/sql_datasource.py, dcs_core/integrations/databases/mssql.py, dcs_core/integrations/databases/postgres.py
=> fix: database quoting

dcs_core/integrations/databases/mssql.py, dcs_core/integrations/databases/sybase.py
-  Sybase IQ/ASE and MSSQL numeric_scale and numeric_precision qyery fixed
=> fix: Sybase and mssql numeric_scale and numeric_precision query

poetry.lock, pyproject.toml, ui/package.json, ui/yarn.lock
Other
___
- Update Python version requirement from 3.9+ to 3.10+
- Add snowflake-connector-python dependency for Snowflake support
- Fix nanoid package version formatting in UI
___
```mermaid
flowchart LR
A["Python 3.9+ requirement"] --> B["Python 3.10+ requirement"]
C["Snowflake extras"] --> D["Add snowflake-connector-python"]
E["nanoid version"] --> F["Fix formatting"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>pyproject.toml</strong><dd><code>Update Python version and Snowflake dependencies</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pyproject.toml …
=> chore(security): update vulnerable packages
